// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HeaderLayout: typeof import('./src/layouts/HeaderLayout.vue')['default']
    Home: typeof import('./src/views/Home.vue')['default']
    Login: typeof import('./src/views/Login.vue')['default']
    LoginCard: typeof import('./src/components/LoginCard.vue')['default']
    MyHeader: typeof import('./src/components/MyHeader.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NSpace: typeof import('naive-ui')['NSpace']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SingleCardLayout: typeof import('./src/layouts/SingleCardLayout.vue')['default']
  }
}

export {}
